# MNIST with Neural Network
I did this exercise to study how a neural network run and learn from data. In this notebook, my intecions were to solve this problem using only basic librarys, as pandas, numpy and matplotlib. I particionated my code in 2 diferrents archives, with classes that refer to the name of each archive.

In [1]:
from neural_network import * 
from neuron_functions import * 

### Reading the data

In [2]:
data_base = pd.read_csv('../data/train.csv')
data_base

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [3]:
data_array = np.array(data_base)
m, n = data_array.shape
np.random.shuffle(data_array) #I did shuffle to divide into train and test
m , n

(42000, 785)

In [4]:
data_test = data_array[0:1000].T
Y_test = data_test[0]
X_test = data_test[1:n]
X_test = X_test / 255

data_train = data_array[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255

### Training

In [5]:
np.random.seed(42)
nn = NeuralNetwork()

In [6]:
W1, b1, W2, b2 = nn.gradient_descent(X_train,Y_train,.1,500)

Iteration:  0
[5 5 5 ... 5 5 5] [3 8 1 ... 8 9 6]
0.08997560975609756
Iteration:  10
[0 0 2 ... 0 0 0] [3 8 1 ... 8 9 6]
0.10485365853658536
Iteration:  20
[0 0 3 ... 0 7 2] [3 8 1 ... 8 9 6]
0.19434146341463415
Iteration:  30
[3 0 1 ... 3 7 6] [3 8 1 ... 8 9 6]
0.5236829268292683
Iteration:  40
[3 8 1 ... 3 9 6] [3 8 1 ... 8 9 6]
0.652390243902439
Iteration:  50
[3 8 1 ... 8 4 6] [3 8 1 ... 8 9 6]
0.7136585365853658
Iteration:  60
[3 8 1 ... 8 4 6] [3 8 1 ... 8 9 6]
0.7589512195121951
Iteration:  70
[3 8 1 ... 8 4 6] [3 8 1 ... 8 9 6]
0.7870731707317074
Iteration:  80
[3 5 1 ... 1 9 6] [3 8 1 ... 8 9 6]
0.7589512195121951
Iteration:  90
[3 8 1 ... 8 9 6] [3 8 1 ... 8 9 6]
0.8035121951219513
Iteration:  100
[3 8 1 ... 8 9 6] [3 8 1 ... 8 9 6]
0.8326829268292683
Iteration:  110
[3 8 1 ... 8 9 6] [3 8 1 ... 8 9 6]
0.8463170731707317
Iteration:  120
[3 8 1 ... 8 9 6] [3 8 1 ... 8 9 6]
0.8549024390243902
Iteration:  130
[3 8 1 ... 8 9 6] [3 8 1 ... 8 9 6]
0.8618536585365854
Iteration:  140

### Test

In [7]:
predictions = nn.make_predictions(X_test,Y_test)

[2 7 6 6 8 9 0 6 5 3 1 1 7 7 3 5 1 2 1 2 5 1 6 6 2 9 3 2 0 8 2 3 7 9 1 6 1
 1 6 3 9 2 8 2 9 0 2 4 5 6 0 4 5 5 8 1 4 1 0 6 2 4 9 8 6 4 4 4 8 9 7 7 6 5
 0 6 5 4 3 6 0 1 2 9 5 5 6 1 6 5 1 9 7 8 0 4 4 3 0 4 2 7 7 8 3 8 8 6 6 7 8
 1 3 9 3 1 6 3 5 9 5 4 2 5 5 8 7 7 8 4 7 3 5 3 5 0 0 8 0 9 6 4 9 9 8 0 4 3
 3 6 0 1 2 9 4 0 0 8 2 4 7 6 6 1 2 4 1 1 4 1 2 4 7 7 6 5 4 9 7 4 6 0 7 3 7
 0 7 6 9 7 4 9 3 9 3 1 8 4 9 7 8 0 2 4 6 0 1 8 5 7 7 3 8 8 0 6 5 5 8 8 6 1
 3 7 3 6 8 1 7 6 4 7 9 1 4 9 0 5 3 4 9 3 0 8 1 3 5 5 0 7 9 3 2 0 6 9 4 7 5
 7 3 6 7 1 2 8 5 2 4 5 0 5 0 4 4 9 2 0 7 4 3 4 6 5 8 5 8 0 4 6 8 7 0 6 4 8
 1 0 8 1 9 3 1 8 6 6 3 5 4 2 5 0 0 9 3 9 6 7 6 3 4 2 8 3 6 2 0 4 6 6 9 6 4
 6 2 3 6 0 6 4 2 6 5 9 6 8 8 5 8 7 7 1 2 4 5 6 4 8 3 3 4 4 6 1 4 4 3 9 8 4
 5 6 4 0 4 2 4 1 0 9 6 6 7 8 7 8 9 1 0 8 0 4 9 1 7 6 2 9 2 3 7 5 8 9 9 6 4
 9 6 5 3 1 6 1 9 1 3 2 1 9 9 9 0 7 9 5 0 8 9 7 4 4 3 6 3 8 0 9 2 0 7 9 7 7
 0 7 9 5 2 1 8 7 6 7 4 7 2 0 6 3 7 6 1 7 7 9 7 2 5 5 2 4 4 9 3 5 6 9 6 0 6
 3 2 9 7 8 2 2 6 7 1 8 3 