# MNIST with Neural Network
I did this exercise to study how a neural network run and learn from data. In this notebook, my intecions were to solve this problem using only basic librarys, as pandas, numpy and matplotlib. I particionated my code in 2 diferrents archives, with classes that refer to the name of each archive.

In [1]:
from neural_network import * 
from neuron_functions import * 

### Reading the data

In [2]:
data_base = pd.read_csv('../data/train.csv')
data_base

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [3]:
data_array = np.array(data_base)
m, n = data_array.shape
np.random.shuffle(data_array) #I did shuffle to divide into train and test
m , n

(42000, 785)

In [4]:
data_test = data_array[0:1000].T
Y_test = data_test[0]
X_test = data_test[1:n]
X_test = X_test / 255

data_train = data_array[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255

### Training

In [5]:
nn = NeuralNetwork()

In [6]:
W1, b1, W2, b2 = nn.gradient_descent(X_train,Y_train,.1,500)

Iteration:  0
[5 5 5 ... 5 5 5] [9 4 1 ... 6 0 1]
0.09068292682926829
Iteration:  10
[0 0 0 ... 0 0 0] [9 4 1 ... 6 0 1]
0.09826829268292683
Iteration:  20
[0 0 3 ... 0 0 3] [9 4 1 ... 6 0 1]
0.18804878048780488
Iteration:  30
[7 4 1 ... 0 0 1] [9 4 1 ... 6 0 1]
0.45107317073170733
Iteration:  40
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.6098780487804878
Iteration:  50
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.7039024390243902
Iteration:  60
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.7609756097560976
Iteration:  70
[4 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.7925365853658537
Iteration:  80
[4 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8160487804878048
Iteration:  90
[4 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8330487804878048
Iteration:  100
[4 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8404146341463414
Iteration:  110
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8491219512195122
Iteration:  120
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8618048780487805
Iteration:  130
[9 4 1 ... 6 0 1] [9 4 1 ... 6 0 1]
0.8698292682926829
Iteration:  1

### Test

In [7]:
predictions = nn.make_predictions(X_test,Y_test)

[0 4 4 9 0 3 0 0 2 4 6 0 4 8 2 4 2 5 6 2 1 3 6 2 4 1 6 4 4 2 7 8 3 9 1 2 2
 1 1 1 2 6 6 4 1 1 1 6 9 6 4 4 1 8 3 6 7 1 1 6 1 7 5 8 4 1 2 0 4 0 2 7 3 7
 8 7 3 3 3 9 8 2 0 6 2 1 2 0 8 6 1 7 9 9 1 3 4 7 0 2 0 0 0 7 6 8 1 8 0 5 9
 4 4 6 2 4 6 6 7 1 0 5 7 8 9 8 8 3 2 4 8 4 1 5 9 9 2 1 1 0 4 3 4 9 6 2 8 7
 1 0 1 6 4 6 9 4 4 5 8 1 7 0 2 2 8 6 2 1 4 1 8 3 6 9 4 4 4 8 3 6 1 3 8 9 2
 4 4 0 6 1 8 1 1 1 6 2 3 0 6 8 6 4 4 7 5 2 5 9 4 5 1 4 1 7 6 7 0 2 9 6 6 6
 5 1 6 7 7 4 3 9 8 1 5 8 6 9 9 8 6 4 1 3 3 1 0 0 7 1 6 0 1 7 8 4 2 9 4 8 2
 3 2 6 0 7 6 2 1 5 9 3 1 1 9 2 8 2 4 4 9 0 1 5 8 4 3 2 8 9 9 7 7 7 3 3 7 7
 3 7 6 4 5 5 3 4 6 6 6 3 9 9 9 9 6 8 7 9 4 2 7 1 9 2 7 7 7 3 4 7 5 0 6 3 8
 4 2 9 0 6 2 4 1 5 0 6 9 4 1 3 7 9 8 7 7 6 5 3 1 7 4 0 0 3 9 4 9 3 0 2 3 4
 5 6 8 4 9 8 2 3 6 0 5 9 6 3 3 9 7 1 1 8 7 9 0 2 4 7 7 5 0 9 5 4 8 8 2 4 6
 9 1 7 9 1 2 3 2 3 3 7 0 4 1 6 2 5 6 3 7 8 7 0 6 1 8 7 7 0 7 6 8 5 6 8 5 7
 9 2 6 8 1 6 5 3 7 1 1 4 9 6 4 8 4 7 0 8 9 8 0 7 1 5 1 6 5 0 5 4 6 1 0 7 4
 0 9 9 3 4 9 8 2 0 9 6 5 